<?php
/*
* This file was automatically generated by Path
* Modify to suit your usage
* 
*/
namespace Path\Http\MiddleWare;


use Path\Http\MiddleWare;
use Path\Http\Request;
use Path\Http\Response;

class IsLoggedUser implements MiddleWare
{

    /**
     * @param Request $request
     * @param Response $response
     * @return mixed
     * @throws \Path\ConfigException
     * @internal param $params
     */
    public function validate(Request $request, Response $response):bool
    {
        return true;
    }

    public function fallBack(Request $request, Response $response)
    {
            return $response->json(["msg" => "This json response is from \"IsLoggedUser\" MiddleWare, you get this response because \$this->validate() returns false"]);
    }
}
