<?php
/**
 * @Author by Sulaiman Adewale.
 * @Date 12/24/2018
 * @Time 12:16 PM
 * @Project Path
 */

namespace Path\Console;


//use Path\Console;

class Create extends CInterface
{
    public $name = "create";
    public $description = "start development server";
    public $arguments = [
        "controller" => [
            "desc" => "Accepts Controller name as argument"
        ],
        "command" => [
            "desc" => "Accepts Custom Command name as argument, e.g: __path create command customCommand"
        ]
    ];

    private $models_path = "Path/Database/Models/";
    private $commands_path = "Path/Commands/";
    private $route_controllers_path = "Path/Controllers/Route/";
    private $live_controllers_path = "Path/Controllers/Live/";

    public function entry(object $params)
    {
        if(isset($params->controller)){
            $this->createModel($params->controller);
        }elseif (isset($params->command)){
            $this->createCommand($params->command);
        }

    }
    private function createCommandBoilerPlate($write_instance,$command_file_name){
        $command_name = $this->ask("Enter command name (if different from the file name): ") ?? strtolower($command_file_name);
        $command_desc = $this->ask("Enter a description for this command: ") ?? "";
        $command_param = $this->ask("Enter a parameter for this command: ");
        $command_param_desc = $this->ask("Enter the parameter's description: ");

        $code = "<?php


namespace Path\Console;


use Path\Console;

class $command_file_name extends CInterface
{


    /*
     * Command Line name
     *
     * @var String
     * */
    public \$name = \"{$command_name}\";
    public \$description = \"{$command_desc}\";
    ";
        if(!is_null($command_param)){
            $code .= PHP_EOL."
    public \$arguments = [
        \"{$command_param}\" => [
            \"desc\" => \"{$command_param_desc}\"
        ]
    ];
            
            ";
        }

        $code .= "

    public function __construct()
    {
    }

    /**
     * @param \$params
     */
    public function entry(object \$params)
    {
        var_dump(\$params);
    }

}
        ";
        fwrite($write_instance,$code);
        echo PHP_EOL.PHP_EOL."[+] ----  Database model boiler plate for --{$command_file_name}-- generated in \"{$this->commands_path}\" ".PHP_EOL;
        fclose($write_instance);


    }
    private function createCommand($command_file_name){
        if(strlen($command_file_name) < 2)
            $command_file_name = $this->ask('Please Specify Command Name');
        $command_file_path = "{$this->commands_path}{$command_file_name}.php";
        if(file_exists($command_file_path)){
            if($this->confirm("Command already exist, do you want to overwrite? ")){
                $command_file_open = fopen($command_file_path,"w");
                $this->createCommandBoilerPlate($command_file_open,$command_file_name);
            }
        }else{
            $command_file_open = fopen($command_file_path,"w");
            $this->createCommandBoilerPlate($command_file_open,$command_file_name);
        }
    }
    private function createModelBoilerPlate($db_model_file,$model_name){
        $model_boiler_plate = "<?php
/*
* This is automatically generated 
* Edit to fit your need
* Powered By: Path
*/

namespace Path\Database\Models;


use Data\Model;

class {$model_name} extends Model
{
    protected \$table_name               = \"".strtolower($model_name)."\";
    protected \$non_writable_cols        = [\"id\"];
    protected \$readable_cols            = [\"id\",\"name\",\"description\"];

    public function __construct()
    {
        parent::__construct();
    }
}";
        //        Write model boiler plate code to file
        fwrite($db_model_file,$model_boiler_plate);
        echo PHP_EOL.PHP_EOL."[+] ----  Database model boiler plate for --{$model_name}-- generated".PHP_EOL;
        fclose($db_model_file);
    }

    private function createLiveControllerBoilerPlate($controller_file, $controller_name, $model_name){
        $watchables = explode(",",$this->ask("Enter Watchable methods, separate with comma if one than one"));

        $boiler_plate = "<?php
/*
* This Live Controller File Was automatically 
* Generated by Path
* Modify to Suite your needs,
* */

namespace Path\\Controller\\Live;

use Path\\Storage\\Caches;
use Path\\Http\\Response;
use Path\\Http\\Watcher;
use Path\\LiveController;
use Path\Database\Models\\$model_name;
use Path\Storage\Sessions;

import(
    \"Core/Classes/Database/Model\",
    \"Path/Database/Models/Admin\"
);

class $controller_name implements LiveController
{
    // this array of methods that can be watched
    // the array key here can either represent a method of dynamic data being set in constructor
    ";
        if(count($watchables) > 0){
            foreach ($watchables as $method){
                $boiler_plate .=" 
    public \$$method = \"initial value\";//Change 'initial value' in constructor of this class'";
            }
        }

        $boiler_plate .= "    
    //every time the watcher checks this Live Controller, it passes some data to it 
    public function __construct(
        Sessions \$sessions,//the session instance that can be used for auth. with the client side
        \$params,//the params parsed from Javascript Path-Watcher
        \$message//message sent from User(client Side)
    )
    {
      
        /*
        *  
        * you should set the value of each properties(which represents methods in this class)
        * to something that changes based on the return value
        * of the method they represents
        *
         */
";
        if(count($watchables) > 0){
            foreach ($watchables as $method){
                $boiler_plate .=" 
        \$this->$method =  \"a dynamic value\";";
            }
        }
        $boiler_plate .="
    }
";
        if(count($watchables) > 0){

            foreach ($watchables as $method){
                $boiler_plate .=" 
public function $method(Response \$response,?String \$message,Sessions \$sessions){
//response here will be sent to client side when \$this->watch_list[\"$method\"]'s value changes
        return \$response->json(['message_sent' => \"hello\"]);
}
        ";
            }

        }

        $boiler_plate .= "        

}
        ";
        //        Write controller boiler plate
        fwrite($controller_file,$boiler_plate);
        echo PHP_EOL.PHP_EOL."[+] ----  Controller boiler plate for --{$model_name}-- generated in \"{$this->live_controllers_path}\" ".PHP_EOL;
        fclose($controller_file);
    }

    private function createRouteControllerBoilerPlate($controller_file, $controller_name, $model_name){
        $contr_boiler_plate = "<?php

/*
* This is automatically generated 
* Edit to fit your need
* Powered By: Path
*/

namespace Path\Controller\Route;


use Path\Controller;
use Path\Http\Request;
use Path\Http\Response;
use Path\Database\Models\\$model_name;
use Path\Storage\Sessions;

import(\"Path/Database/Models/{$model_name}\");

class {$controller_name} implements Controller
{
    private \$session;
    public function __construct()
    {
        \$this->session = new Sessions();
    }
    public function fetchAll(Request \$request,Response \$response){
//     return a response here
        return \$response->json(['this is response from {$controller_name} Controller']);
    }

}";



//        Write controller boiler plate
        fwrite($controller_file,$contr_boiler_plate);
        echo PHP_EOL.PHP_EOL."[+] ----  Controller boiler plate for --{$model_name}-- generated in \"{$this->route_controllers_path}\" ".PHP_EOL;
        fclose($controller_file);
    }
    private function createModel($controller_name){
        if($controller_name === true){
            $controller_name = $this->ask("Enter Controller's name",true);
        }
//        Create file in Database/Models
//        Create file controllers/

        if(!$this->confirm("Do you have existing Model for your controller? ")){
            $_model_name = $this->ask("Enter new Model's Name:",true);
            $_db_model_file = "{$this->models_path}{$_model_name}.php";
            if(file_exists($_db_model_file)){
                if($this->confirm("{$_model_name} Database model Already exists, Override?")){
                    $db_model_file = fopen($_db_model_file,"w");
                    $this->createModelBoilerPlate($db_model_file,$_model_name);
                }
            }else{
                $db_model_file = fopen($_db_model_file,"w");
                $this->createModelBoilerPlate($db_model_file,$_model_name);
            }
            $new_model_name = $_model_name;
        }else{
            $new_model_name = $this->ask("Enter Existing Model's Name",true);
        }

        if($controller_type = strtolower($this->confirm('Controller Type','Route','Live'))){
            $_controller_file = "{$this->route_controllers_path}{$controller_name}.php";
            if(file_exists($_controller_file)){
                if($this->confirm("{$controller_name} Controller Already exists, Override?",['Yes','y'],['No','n'])){
                    $controller_file = fopen($_controller_file,"w");
                    $this->createRouteControllerBoilerPlate($controller_file,$controller_name,$new_model_name);
                }
            }else{
                $controller_file = fopen($_controller_file,"w");
                $this->createRouteControllerBoilerPlate($controller_file,$controller_name,$new_model_name);
            }
        }else{
//            TODO: implement Live controller generation here
            $this->write('creating live controller');
            $_controller_file = "{$this->live_controllers_path}{$controller_name}.php";
            if(file_exists($_controller_file)){
                if($this->confirm("{$controller_name} Controller Already exists, Override?",['Yes','y'],['No','n'])){
                    $controller_file = fopen($_controller_file,"w");
                    $this->createLiveControllerBoilerPlate($controller_file,$controller_name,$new_model_name);
                }
            }else{
                $controller_file = fopen($_controller_file,"w");
                $this->createLiveControllerBoilerPlate($controller_file,$controller_name,$new_model_name);
            }
        }
        echo PHP_EOL.PHP_EOL."[+] ---- CLOSING -----".PHP_EOL.PHP_EOL;

        echo $controller_name;
    }
}
