<?php
/*
* This FIle was automatically generated By Path
* Modify to your advantage
*/

namespace Path\App\Database\Migration;


use Path\Core\Database\Model;
use Path\Core\Database\Prototype;
use Path\Core\Database\Structure;
use Path\Core\Database\Table;



class Blog implements Table
{
    public $table_name = "blog";
    public $primary_key = "id";
    public function install(Structure &$table)
    {
        $table->column('title')
                ->type('text')
                ->nullable();
        $table->column('body')
            ->type('text')
            ->nullable();
        $table->column('author_id')
            ->type('int')
            ->references('author(id)');
    }

    public function uninstall()
    {
    }

    public function populate(Model $table)
    {

    }

    public function update(Structure &$table)
    {

    }
}
