<?php
/*
* This FIle was automatically generated By Path
* Modify to your advantage
*/

namespace Path\Database\Migration;


use Path\Database\Model;
use Path\Database\Prototype;
use Path\Database\Structure;
use Path\Database\Table;

import(
    "core/classes/Database/Prototype",
    "core/classes/Database/Table",
    "core/classes/Database/Structure"
);

class Posts implements Table
{
    public $table_name = "posts";
    public $primary_key = "id";
    public function install(Structure &$table)
    {
        $table->column("name")
            ->type("TEXT")
            ->nullable();

    }

    public function uninstall()
    {
    }

    public function populate(Model $table)
    {
        $table->insert([
            "name" => "I am testing"
        ]);
    }

    public function update(Structure &$table)
    {
        $table->rename("name")
            ->to("new_col_name")
            ->type("TEXT")
            ->nullable();
    }
}