<?php
/*
* This FIle was automatically generated By Path
* Modify to your advantage
*/

namespace Path\Database\Migration;


use Path\Database\Model;
use Path\Database\Prototype;
use Path\Database\Structure;
use Path\Database\Table;

import(
    "core/classes/Database/Prototype",
    "core/classes/Database/Table",
    "core/classes/Database/Structure"
);

class User implements Table
{
    public $table_name = "user";
    public $primary_key = "id";
    public function install(Structure &$table)
    {
        $table->column("name")
            ->type("text")
            ->nullable();

        $table->column("profile")
            ->type("json")
            ->nullable();

    }

    public function uninstall()
    {
    }

    public function populate(Model $table)
    {

    }

    public function update(Structure &$table)
    {
    }
}